apiVersion: v2
description: Reloader for Kubernetes. Watches ConfigMaps and Secrets and triggers rolling updates of Deployments, DaemonSets, StatefulSets. Uses Stakater chart.
name: reloader
version: 1.0.0
dependencies:
  - name: reloader
    version: "2.2.7"
    repository: https://stakater.github.io/stakater-charts
  - name: onepassworditem
    version: "1.1.1"
    repository: https://expectedbehaviors.github.io/OnePasswordItem-helm
